# general settings
name: TanColorize_FastSprint
model_type: ColorModel
scale: 1
num_gpu: 1
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: CustomNet
    type: LabDataset
    dataroot_gt: "C:/Users/nimet/Documents/IIT/L6/FYP/Dataset/SkinTan"
    meta_info_file: meta_train.txt
    phase: train
    io_backend:
      type: disk
    gt_size: 128
    batch_size_per_gpu: 32
    num_worker_per_gpu: 8
    use_shuffle: true
    # Mandatory augmentation flags to fix KeyError
    use_hflip: true
    use_rot: false
    do_cutmix: false
    cutmix_p: 0.5
    do_fmix: false
    fmix_p: 0.5

  val:
    name: CustomNet
    type: LabDataset
    dataroot_gt: "C:/Users/nimet/Documents/IIT/L6/FYP/Dataset/Datase_Validation"
    meta_info_file: meta_val.txt
    phase: val
    io_backend:
      type: disk
    gt_size: 128 
    batch_size_per_gpu: 8
    use_shuffle: false
    # Mandatory augmentation flags to fix KeyError
    use_hflip: false
    use_rot: false
    do_cutmix: false
    cutmix_p: 0.5
    do_fmix: false
    fmix_p: 0.5

# network structures
network_g:
  type: TanColorize
  encoder_name: convnext-t 
  encoder_from_pretrain: True
  num_queries: 32
  num_scales: 3
  dec_layers: 2
  last_norm: Spectral
  num_output_channels: 2
  decoder_name: MultiScaleColorDecoder
  do_normalize: false

network_d:
  type: DynamicUNetDiscriminator
  nf: 16
  n_channels: 3

# path
path:
  pretrain_network_g: ~
  strict_load_g: false
  resume_state: ~

# training settings
train:
  use_amp: true
  color_enhance: false
  optim_g:
    type: AdamW
    lr: !!float 4e-4
    weight_decay: 0.01
    betas: [0.9, 0.99]
  optim_d:
    type: Adam
    lr: !!float 4e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  total_iter: 5000
  warmup_iter: -1
  scheduler:
    type: MultiStepLR
    milestones: [3000, 4500]
    gamma: 0.5

  # Speed-optimized Losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      "conv5_4": 1.0
    vgg_type: vgg19
    use_input_norm: true
    range_norm: false
    perceptual_weight: 1.0
    style_weight: 0
    criterion: l1
  gan_opt:
    type: GANLoss
    gan_type: vanilla
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: 0.05

# validation settings
val:
  val_freq: 5000
  save_img: true
  pbar: true
  metrics:
    # fid:
    #   type: calculate_fid
    #   better: lower

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: 500
  use_tb_logger: true
  save_snapshot_freq: 1000